sonar.projectKey=ipssidhu-ai_8.2CDevSecOps
sonar.organization=Ishatpartap
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,tests/**
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
